const colors = {
  light: {
    text: '#0F172A',
    tint: '#5B61FF',
    background: '#F4F7FC',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    primary: '#5B61FF',
    primaryForeground: '#FFFFFF',
    secondary: '#EAF0F8',
    secondaryForeground: '#334155',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    accent: '#8B5CF6',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#FFFFFF',
    success: '#10B981',
    warning: '#F59E0B',
  },
  dark: {
    text: '#0F172A',
    tint: '#5B61FF',
    background: '#F4F7FC',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    primary: '#5B61FF',
    primaryForeground: '#FFFFFF',
    secondary: '#EAF0F8',
    secondaryForeground: '#334155',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    accent: '#8B5CF6',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#FFFFFF',
    success: '#10B981',
    warning: '#F59E0B',
  },
  radius: 24,
};

export default colors;